Integration with Scaffold-stark: Updated develop branch to use latest version of scaffold-stark
The-Marquis-Gaming/themarquis-ui pull request #112
Opened 2024-12-20 15:31 UTC by michojekunle

# Integration with Scaffold-stark: Updated develop branch to use latest version of scaffold-stark

Fixes #93 

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

2024-12-20 20:56 UTC, michojekunle commented
Hi @gianalarcon I've made the requested changes regarding this issue #93 linked to this PR #111

Please review

2024-12-21 10:44 UTC, gianalarcon commented
`yarn compile` & `yarn test` not working
![image](https://github.com/user-attachments/assets/7e3e6d95-25d3-4301-af73-d12809beedb9)

2024-12-21 11:21 UTC, gianalarcon commented
Pls also sync with test-develop branch again

2024-12-21 13:47 UTC, michojekunle commented
> `yarn compile` & `yarn test` not working ![image](https://private-user-images.githubusercontent.com/22782504/397921804-7e3e6d95-25d3-4301-af73-d12809beedb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg5MDMsIm5iZiI6MTczNDc4ODYwMywicGF0aCI6Ii8yMjc4MjUwNC8zOTc5MjE4MDQtN2UzZTZkOTUtMjVkMy00MzAxLWFmNzMtZDEyODA5YmVlZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzNDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjA1NmVhODEwNjJkZWIxNDg2YTBjN2U0ZDI5YTExNjQ1Mzg5MDlkMzUwYmY1MmI1Njg1OTE2ZjBiNWMzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.puiUAxE05un88oy8jADZ8aANFXWs5evgCvvLf_A1yos)

Alright on this now 🚀

2024-12-21 13:49 UTC, michojekunle commented
> Pls also sync with test-develop branch again

okay sure

2024-12-21 23:05 UTC, michojekunle commented
> > Pls also sync with test-develop branch again
> 
> okay sure

I've synced now with the latest update from the test-develop branch

2024-12-21 23:07 UTC, michojekunle commented
> > `yarn compile` & `yarn test` not working ![image](https://private-user-images.githubusercontent.com/22782504/397921804-7e3e6d95-25d3-4301-af73-d12809beedb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg5MDMsIm5iZiI6MTczNDc4ODYwMywicGF0aCI6Ii8yMjc4MjUwNC8zOTc5MjE4MDQtN2UzZTZkOTUtMjVkMy00MzAxLWFmNzMtZDEyODA5YmVlZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzNDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjA1NmVhODEwNjJkZWIxNDg2YTBjN2U0ZDI5YTExNjQ1Mzg5MDlkMzUwYmY1MmI1Njg1OTE2ZjBiNWMzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.puiUAxE05un88oy8jADZ8aANFXWs5evgCvvLf_A1yos)
> 
> Alright on this now 🚀

I've fixed this

`yarn compile` and `yarn test` now working

![image](https://github.com/user-attachments/assets/a0527918-5028-40d5-84ad-a2cae1c35173)

2024-12-21 23:11 UTC, michojekunle commented
Hi @gianalarcon Thank you so much for the review once again 

I've made the requested changes 

Please review 🤩

2024-12-22 04:36 UTC, gianalarcon commented
Hi @Buuh2511 pls help me to check this pr. All changes in snfoundry are ok.

@michojekunle pls fix it in order to pass lint. @Buuh2511 can support here as well

2024-12-22 04:38 UTC, michojekunle commented
> Hi @Buuh2511 pls help me to check this pr. All changes in snfoundry are ok.
> 
> @michojekunle pls fix it in order to pass lint. @Buuh2511 can support here as well 

Alright on it already, just got the notification of the lint error this morning fixing it now.

2024-12-23 07:48 UTC, Buuh2511 commented
Some bugs from UI
![image](https://github.com/user-attachments/assets/094626b3-f48a-445b-8343-f91134db6d1c)
![image](https://github.com/user-attachments/assets/9666d8b8-9604-4b40-9180-63db8bf9d2ed)
![image](https://github.com/user-attachments/assets/9c03adff-2bde-4b97-a1dd-4667901bf952)
![image](https://github.com/user-attachments/assets/c8164a1e-871f-4987-9f1c-73ab59ff7bbb)
![image](https://github.com/user-attachments/assets/2c5b5674-114f-42e5-8d30-eaf3606c3ce1)
![image](https://github.com/user-attachments/assets/92391bd4-19ea-473c-ae36-519dfd10b6cb)

2024-12-23 08:00 UTC, gianalarcon commented
We shouldn't change anything on the specific UI of the Marquis, we have update scaffold components and hooks, but our landing page design shouldn't change. Please try to fix it asap @michojekunle, deadline coming,  we will be active to review your work, thanks

2024-12-23 08:24 UTC, michojekunle commented
> We shouldn't change anything on the specific UI of the Marquis, we have update scaffold components and hooks, but our landing page design shouldn't change. Please try to fix it asap @michojekunle, deadline coming, we will be active to review your work, thanks

Alright on it now

2024-12-23 08:28 UTC, Buuh2511 requested changes
- Face on some issues with nextjs image - fresh clone
- Landing page background color has been changed
- Using wrong connect wallet button component
- [Here ](https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=0-1&p=f&t=yEQ31BpYVP1JJSH7-0)is our Figma UI, need to compare to your currenly version or compare to UI on branch main  before Review
- Need to add yarn next:test in package.json


**Missing**
1. [test folder](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/services/web3/__test__) 
2. [test folder](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/app/debug)
3. [test folder ](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/hooks/scaffold-stark/__tests__)
4. useDataTransaction

**Havent updated** 
- useScaffoldContract 
- useScaffoldEventHistory 
- useScaffoldStarkProfile 
- /component/scaffold-stark/ConnectModal.tsx 
- /component/scaffold-stark/AddressInfoDropdown.tsx 
- /component/scaffold-stark/index.tsx 
- /component/scaffold-stark/ Wallet.tsx 




**Finnaly**
- Make sure pass all test file
- All features must work
- UI must the same with main branch or Figma

2024-12-23 10:00 UTC, michojekunle commented
> * Face on some issues with nextjs image - fresh clone
> * Landing page background color has been changed
> * Using wrong connect wallet button component
> * [Here ](https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=0-1&p=f&t=yEQ31BpYVP1JJSH7-0)is our Figma UI, need to compare to your currenly version or compare to UI on branch main  before Review
> * Need to add yarn next:test in package.json
> 
> **Missing**
> 
> 1. [test folder](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/services/web3/__test__)
> 2. [test folder](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/app/debug)
> 3. [test folder ](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/27938d4975ed80af0db5d96edee14531f5a520ec/packages/nextjs/hooks/scaffold-stark/__tests__)
> 4. useDataTransaction
> 
> **Havent updated**
> 
> * useScaffoldContract
> * useScaffoldEventHistory
> * useScaffoldStarkProfile
> * /component/scaffold-stark/ConnectModal.tsx
> * /component/scaffold-stark/AddressInfoDropdown.tsx
> * /component/scaffold-stark/index.tsx
> * /component/scaffold-stark/ Wallet.tsx
> 
> **Finnaly**
> 
> * Make sure pass all test file
> * All features must work
> * UI must the same with main branch or Figma

Alright, Thank you so much for the review, On it already

2024-12-23 12:07 UTC, gianalarcon commented
is it ready right? apply `yarn format` to pass lint

2024-12-23 12:22 UTC, michojekunle commented
> is it ready right? apply `yarn format` to pass lint

Yes just did, Noticed another run failing will check it out now

2024-12-23 12:23 UTC, michojekunle commented
> > is it ready right? apply `yarn format` to pass lint
> 
> Yes just did, Noticed another run failing will check it out now

Noticed some tests are failing, will fix now

2024-12-23 12:24 UTC, gianalarcon commented
> > > is it ready right? apply `yarn format` to pass lint
> > 
> > 
> > Yes just did, Noticed another run failing will check it out now
> 
> Noticed some tests are failing, will fix now

`yarn format` should be ok

2024-12-23 13:00 UTC, Buuh2511 commented
Is this PR ready @michojekunle👀👀

2024-12-23 13:15 UTC, michojekunle commented
> Is this PR ready @michojekunle👀👀

Yes, all tests passing now 🤩

2024-12-23 13:17 UTC, michojekunle commented
Hi @Buuh2511 @gianalarcon made the requested changes now and the UI has been fixed all previously omitted tests have been added and all tests are passing now

Please Review

2024-12-23 13:36 UTC, Buuh2511 commented
wr
![image](https://github.com/user-attachments/assets/1d66272c-8d55-41fc-a2dd-ac43e29300b6)

2024-12-23 13:44 UTC, michojekunle commented
> wrong UI at /signup
> ![image](https://github.com/user-attachments/assets/1d66272c-8d55-41fc-a2dd-ac43e29300b6)
> 
> can u make Referral Link such as : http://localhost:3000/signup?.... (if text long is longer than width box)
> ![image](https://github.com/user-attachments/assets/7eb3b574-211a-4499-958e-0994bf181144)
> 
> 

Alright on this now

2024-12-23 14:00 UTC, Buuh2511 commented
Every file test on packages/nextjs/hooks/scaffold-stark/__tests__should be run when yarn test:nextjs

2024-12-23 14:07 UTC, Buuh2511 commented
Still havent updated : 
1. /component/scaffold-stark/CustomConnectButton/ConnectModal.tsx
2. /component/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
3. /component/scaffold-stark/CustomConnectButton/GenericModal.tsx
4. /component/scaffold-stark/CustomConnectButton/index.tsx
5. /component/scaffold-stark/CustomConnectButton/ Wallet.tsx
6. /component/scaffold-stark/CustomConnectButton/WrongNetworkDropdown.tsx

2024-12-23 14:15 UTC, michojekunle commented
> Still havent updated : 
> 1. /component/scaffold-stark/CustomConnectButton/ConnectModal.tsx
> 2. /component/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
> 3. /component/scaffold-stark/CustomConnectButton/GenericModal.tsx
> 4. /component/scaffold-stark/CustomConnectButton/index.tsx
> 5. /component/scaffold-stark/CustomConnectButton/ Wallet.tsx
> 6. /component/scaffold-stark/CustomConnectButton/WrongNetworkDropdown.tsx

Hi @Buuh2511 I've updated all of these components to match the latest updates on scaffold-stark-2, to the latest commit on the scaffold stark 2 main branch

I carefully integrated the changes that were made and removed the unnecessary changes that doesn't conform with The Marquis Game UI 

Please check once

2024-12-23 14:31 UTC, Buuh2511 commented
> > Still havent updated :
> > 
> > 1. /component/scaffold-stark/CustomConnectButton/ConnectModal.tsx
> > 2. /component/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
> > 3. /component/scaffold-stark/CustomConnectButton/GenericModal.tsx
> > 4. /component/scaffold-stark/CustomConnectButton/index.tsx
> > 5. /component/scaffold-stark/CustomConnectButton/ Wallet.tsx
> > 6. /component/scaffold-stark/CustomConnectButton/WrongNetworkDropdown.tsx
> 
> Hi @Buuh2511 I've updated all of these components to match the latest updates on scaffold-stark-2, to the latest commit on the scaffold stark 2 main branch
> 
> I carefully integrated the changes that were made and removed the unnecessary changes that doesn't conform with The Marquis Game UI
> 
> Please check once

got it, then u just have to sync with scaffold-stark-2, no need to change to conform with The Marquis Game UI . We need all of them in the future

2024-12-23 14:36 UTC, michojekunle commented
> > > Still havent updated :
> > > 
> > > 1. /component/scaffold-stark/CustomConnectButton/ConnectModal.tsx
> > > 2. /component/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
> > > 3. /component/scaffold-stark/CustomConnectButton/GenericModal.tsx
> > > 4. /component/scaffold-stark/CustomConnectButton/index.tsx
> > > 5. /component/scaffold-stark/CustomConnectButton/ Wallet.tsx
> > > 6. /component/scaffold-stark/CustomConnectButton/WrongNetworkDropdown.tsx
> > 
> > Hi @Buuh2511 I've updated all of these components to match the latest updates on scaffold-stark-2, to the latest commit on the scaffold stark 2 main branch
> > 
> > I carefully integrated the changes that were made and removed the unnecessary changes that doesn't conform with The Marquis Game UI
> > 
> > Please check once
> 
> got it, then u just have to sync with scaffold-stark-2, no need to change to conform with The Marquis Game UI . We need all of them in the future

Alright but this means we'll have the connect button UI and modal and AddressInfoDropdown component not rhyme with the UI 

Should I go on with it.

2024-12-23 14:38 UTC, Buuh2511 commented
> Alright but this means we'll have the connect button UI and modal and AddressInfoDropdown component not rhyme with the UI

I understand there will be some conflicts, you can create separate file to keep current version

2024-12-23 19:18 UTC, michojekunle commented
Hi @Buuh2511 Please have a look

2024-12-24 03:11 UTC, Buuh2511 commented
Gm @michojekunle, can u try to fix asap some issue that i will leave under this comment

2024-12-24 03:21 UTC, michojekunle commented
> Gm @michojekunle, can u try to fix asap some issue that i will leave under this comment

Yes sure, Gm ser

2024-12-24 03:30 UTC, Buuh2511 commented
- [ ] Referal link should long as such as box's width, if longer => try to display ... at the end of string
<img width="542" alt="Screenshot 2024-12-24 at 10 14 52 AM" src="https://github.com/user-attachments/assets/0c709ebb-d591-4bab-8afc-981e5f813eda" />

- [ ] Currently version only config for test environment, u can have a quick check [here](https://github.com/The-Marquis-Gaming/themarquis-ui/blob/1330d181b11b2332a23034e5c75c6a913c34badd/packages/nextjs/scaffold.config.ts#L12), so if u are connecting to mainnet, button should be a wrong network. Although user reload page, still keep wrong button if connected wrong chain
<img width="312" alt="Screenshot 2024-12-24 at 10 23 48 AM" src="https://github.com/user-attachments/assets/2eb77ed5-eabf-45e5-a3b3-76f498193946" />

- [ ] The avatar should be from Argentx or Bravoos wallet. If connected Argentx => display icon argentx. If connected Bravoos => display icon bravoos
<img width="307" alt="Screenshot 2024-12-24 at 10 09 47 AM" src="https://github.com/user-attachments/assets/2c319f91-9123-4b22-afd5-74c4f5488c00" />


- After connected correct chain, we can tracking balance and display here
<img width="1426" alt="Screenshot 2024-12-24 at 10 28 15 AM" src="https://github.com/user-attachments/assets/8001f6f9-4dbc-4165-8fab-bb3c1713585f" />

2024-12-24 03:36 UTC, michojekunle commented
> * [ ]  Referal link should long as such as box's width, if longer => try to display ... at the end of string
> 
> <img alt="Screenshot 2024-12-24 at 10 14 52 AM" width="542" src="https://private-user-images.githubusercontent.com/57097047/398306554-0c709ebb-d591-4bab-8afc-981e5f813eda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTE1NjQsIm5iZiI6MTczNTAxMTI2NCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzMDY1NTQtMGM3MDllYmItZDU5MS00YmFiLThhZmMtOTgxZTVmODEzZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OWU0NzYwNmI3ZmY2MzU3NjIwMzRjNDJjY2E1ZDJhNTcwYzEyYmYyZDUyMzU0MTc3MDIyNjMwMTU1YzQzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gcze3hNTkhy7rP27mkBcz4Ale1lOi16hqfOrd1eS_OY">
> * [ ]  Currently version only config for test environment, u can have a quick check [here](https://github.com/The-Marquis-Gaming/themarquis-ui/blob/1330d181b11b2332a23034e5c75c6a913c34badd/packages/nextjs/scaffold.config.ts#L12), so if u are connecting to mainnet, button should be a wrong network. Although user reload page, still keep wrong button if connected wrong chain
> 
> <img alt="Screenshot 2024-12-24 at 10 23 48 AM" width="312" src="https://private-user-images.githubusercontent.com/57097047/398307798-2eb77ed5-eabf-45e5-a3b3-76f498193946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTE1NjQsIm5iZiI6MTczNTAxMTI2NCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzMDc3OTgtMmViNzdlZDUtZWFiZi00NWU1LWEzYjMtNzZmNDk4MTkzOTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYTMyMDcyZDZiNzE0ZDE4ZWUzZThlNTdjMWUxOTQyMmFlZTY5ZWFkODRmZDNmNTU1ZjE5OWM1NTIzZTE5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DHSm2qdbfTVu7WrLLBWEvhtE258hVJlcn5vl7plf674">
> * [ ]  The avatar should be from Argentx or Bravoos wallet. If connected Argentx => display icon argentx. If connected Bravoos => display icon bravoos
> 
> <img alt="Screenshot 2024-12-24 at 10 09 47 AM" width="307" src="https://private-user-images.githubusercontent.com/57097047/398306773-2c319f91-9123-4b22-afd5-74c4f5488c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTE1NjQsIm5iZiI6MTczNTAxMTI2NCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzMDY3NzMtMmMzMTlmOTEtOTEyMy00YjIyLWFmZDUtNzRjNGY1NDg4YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNGNmYmQ0YjFiNWRiM2Q5NzBiNjIzNjdlNDZhOTNiNzVjMzgwYTE5NGQ1MWRhOWRhZWFhZDQzNWY0ZTYzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XLNE2Br1wXbe8VyI1yPv-FB5cfQ5EXlc88LW_yHKEAc">
> * [ ]  After connected correct chain, we can tracking balance and display here
> 
> <img alt="Screenshot 2024-12-24 at 10 28 15 AM" width="1426" src="https://private-user-images.githubusercontent.com/57097047/398308525-8001f6f9-4dbc-4165-8fab-bb3c1713585f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTE1NjQsIm5iZiI6MTczNTAxMTI2NCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzMDg1MjUtODAwMWY2ZjktNGRiYy00MTY1LThmYWItYmIzYzE3MTM1ODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZGY2MjMzNzQxNjQxZjFlNTM2YTY3YTRkNjI0ZjQwMTBhN2MyOTk4YjM2ZTA3ZjliNmFjMmE2OTZlYjhmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ieo8OnliEkTlMVWuDWX4mIFTo4mbqIyLLaCFetjK_Uw">
> * [ ]  the same bug from deposit page
> 
> <img alt="Screenshot 2024-12-24 at 10 32 49 AM" width="1791" src="https://private-user-images.githubusercontent.com/57097047/398309036-ed3fc2d8-1bf6-4894-bbad-4e3ca99667f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTE1NjQsIm5iZiI6MTczNTAxMTI2NCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzMDkwMzYtZWQzZmMyZDgtMWJmNi00ODk0LWJiYWQtNGUzY2E5OTY2N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDE1NTg5OWU3NTdkNDQwMWVkYTg5ZGZmODEwN2I2NDY2NmI4ZjNiOGQ3OWY4NmY4ZmRiOTZiNWM4ZTA2NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SepI7dzpB_DQnCzTglY-Fh9W8AOgzJU5CvfK3t53VfM">

Alright on it now

2024-12-24 06:21 UTC, Buuh2511 commented
Is this ready for review ? @michojekunle

2024-12-24 06:26 UTC, michojekunle commented
> Is this ready for review ? @michojekunle

Partly ser for the changes made so far, Only change remaining is for the wrong network button persistency

2024-12-24 06:40 UTC, Buuh2511 commented
> > Is this ready for review ? @michojekunle
> 
> Partly ser for the changes made so far, Only change remaining is for the wrong network button persistency

btw, u can have a quick look on [this](https://themarquis.xyz/) 
Every feature should be work the same with that

2024-12-24 07:19 UTC, Buuh2511 commented
> > > Is this ready for review ? @michojekunle
> > 
> > 
> > Partly ser for the changes made so far, Only change remaining is for the wrong network button persistency
> 
> btw, u can have a quick look on [this](https://themarquis.xyz/) Every feature should be work the same with that

Are u still working on this ? @michojekunle

2024-12-24 07:23 UTC, michojekunle commented
> > > > Is this ready for review ? @michojekunle
> > > 
> > > 
> > > Partly ser for the changes made so far, Only change remaining is for the wrong network button persistency
> > 
> > btw, u can have a quick look on [this](https://themarquis.xyz/) Every feature should be work the same with that
> 
> Are u still working on this ? @michojekunle 

Yes sorry for the delay, I haven't gotten it to work yet, I'm still on it

2024-12-24 07:41 UTC, michojekunle commented
@Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed

Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲

2024-12-24 08:03 UTC, Buuh2511 commented
Make sure your changes will be work well on another page, i just found new bugs on UI
![Screenshot 2024-12-24 at 3 01 56 PM](https://github.com/user-attachments/assets/3cdd50f9-295c-4cce-b20a-d978e1c07fcd)

2024-12-24 08:09 UTC, Buuh2511 commented
> Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjc3MjQsIm5iZiI6MTczNTAyNzQyNCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4MDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDBjOTgzZjVhZjVlMjllNjcyNDJkMDA3ZGIwYTVhMGI2Mjc0Mzk5ZGYwZWYxMjNkZGNhYTE2NzAxODA4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ZIxAURw7wFWhVU-dB3ThYgb-34KGYI1pXyXWE4frXs)

Still cant tracking balance wallet when switch page or reload page, this bug happen in somtime

2024-12-24 08:11 UTC, michojekunle commented
> Make sure your changes will be work well on another page, i just found new bugs on UI
> ![Screenshot 2024-12-24 at 3 01 56 PM](https://github.com/user-attachments/assets/3cdd50f9-295c-4cce-b20a-d978e1c07fcd)
> 

Will fix this now,

2024-12-24 08:12 UTC, michojekunle commented
> > Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjc3MjQsIm5iZiI6MTczNTAyNzQyNCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4MDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDBjOTgzZjVhZjVlMjllNjcyNDJkMDA3ZGIwYTVhMGI2Mjc0Mzk5ZGYwZWYxMjNkZGNhYTE2NzAxODA4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ZIxAURw7wFWhVU-dB3ThYgb-34KGYI1pXyXWE4frXs)
> 
> Still cant tracking balance wallet when switch page or reload page, this bug happen in somtime

Alright will look into this again

2024-12-24 08:18 UTC, Buuh2511 commented
> @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> 
> Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲

U can take a look : useTargetNetwork to resolve

2024-12-24 08:37 UTC, Buuh2511 requested changes
Have to update base on comment

2024-12-24 08:39 UTC, michojekunle commented
> Have to update base on comment

Alright on it now

2024-12-24 08:40 UTC, michojekunle commented
> Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjk5MjAsIm5iZiI6MTczNTAyOTYyMCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzhkMzY2ZGEzOGI1NGE2ZDY5MTY4YTdkZDNmZWQ1ZjU4N2Y0YjNjNzE5YjMyODg3NmQzYzI2ZTQ1Y2JiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P9uqra8H5Npq40L8dpzTld24_d3fdx2cfJuxZYYem0)

fixed this now

2024-12-24 08:44 UTC, Buuh2511 commented
> > Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjk5MjAsIm5iZiI6MTczNTAyOTYyMCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzhkMzY2ZGEzOGI1NGE2ZDY5MTY4YTdkZDNmZWQ1ZjU4N2Y0YjNjNzE5YjMyODg3NmQzYzI2ZTQ1Y2JiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P9uqra8H5Npq40L8dpzTld24_d3fdx2cfJuxZYYem0)
> 
> fixed this now

but, u can see when click on invite friend in Marquis wallet => become wrong UI

2024-12-24 08:47 UTC, Buuh2511 commented
Can u also fix at this section a bit, when user logged "Already have an account? Login" will be disappear, so need to alignment spacing here
![Screenshot 2024-12-24 at 3 44 50 PM](https://github.com/user-attachments/assets/e1c0dd52-9b1a-48d5-8016-09468abfd188)

2024-12-24 09:02 UTC, michojekunle commented
> > > Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjk5MjAsIm5iZiI6MTczNTAyOTYyMCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzhkMzY2ZGEzOGI1NGE2ZDY5MTY4YTdkZDNmZWQ1ZjU4N2Y0YjNjNzE5YjMyODg3NmQzYzI2ZTQ1Y2JiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P9uqra8H5Npq40L8dpzTld24_d3fdx2cfJuxZYYem0)
> > 
> > fixed this now
> 
> but, u can see when click on invite friend in Marquis wallet => become wrong UI

Yes already committed a change to fix this

2024-12-24 09:06 UTC, michojekunle commented
> > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > 
> > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> 
> U can take a look : useTargetNetwork to resolve

Based on this the issue I have is that no matter the network that is currently connected to my dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network. 

What could be the issue or am I missing something

2024-12-24 09:14 UTC, Buuh2511 commented
> > > > Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjk5MjAsIm5iZiI6MTczNTAyOTYyMCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzhkMzY2ZGEzOGI1NGE2ZDY5MTY4YTdkZDNmZWQ1ZjU4N2Y0YjNjNzE5YjMyODg3NmQzYzI2ZTQ1Y2JiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P9uqra8H5Npq40L8dpzTld24_d3fdx2cfJuxZYYem0)
> > > 
> > > 
> > > fixed this now
> > 
> > 
> > but, u can see when click on invite friend in Marquis wallet => become wrong UI
> 
> Yes already committed a change to fix this

this should be bigger on PC
![Screenshot 2024-12-24 at 4 13 33 PM](https://github.com/user-attachments/assets/95198424-1bc3-4aca-a4a1-dff58869da39)

2024-12-24 09:16 UTC, Buuh2511 commented
> > > > > Make sure your changes will be work well on another page, i just found new bugs on UI ![Screenshot 2024-12-24 at 3 01 56 PM](https://private-user-images.githubusercontent.com/57097047/398359564-3cdd50f9-295c-4cce-b20a-d978e1c07fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjk5MjAsIm5iZiI6MTczNTAyOTYyMCwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNTk1NjQtM2NkZDUwZjktMjk1Yy00Y2NlLWIyMGEtZDk3OGUxYzA3ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA4NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzhkMzY2ZGEzOGI1NGE2ZDY5MTY4YTdkZDNmZWQ1ZjU4N2Y0YjNjNzE5YjMyODg3NmQzYzI2ZTQ1Y2JiZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P9uqra8H5Npq40L8dpzTld24_d3fdx2cfJuxZYYem0)
> > > > 
> > > > 
> > > > fixed this now
> > > 
> > > 
> > > but, u can see when click on invite friend in Marquis wallet => become wrong UI
> > 
> > 
> > Yes already committed a change to fix this
> 
> this should be bigger on PC ![Screenshot 2024-12-24 at 4 13 33 PM](https://private-user-images.githubusercontent.com/57097047/398375688-95198424-1bc3-4aca-a4a1-dff58869da39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzE5NDYsIm5iZiI6MTczNTAzMTY0NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzNzU2ODgtOTUxOTg0MjQtMWJjMy00YWNhLWE0YTEtZGZmNTg4NjlkYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA5MTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMjhiZTNlNWY5MDg2NTNhMTMyM2Y2NzQyMDk0NGZiY2Q5YmVlNDQwNGIzODAzYTM4NDM2ZWNkNTc2MDFmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NDM8B-804ZnUwf2PKiEd-UK5Am2D-add5XrCqU6knN0)

At least, equal to this
![Screenshot 2024-12-24 at 4 14 44 PM](https://github.com/user-attachments/assets/ee261d49-539a-47ad-8357-b70c2ba0b6df)

2024-12-24 09:50 UTC, Buuh2511 commented
> > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > 
> > 
> > U can take a look : useTargetNetwork to resolve
> 
> Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> 
> What could be the issue or am I missing something

yes, that why we need to update carefully, so u can tracking chain ID by
`const chainId = await provider.provider.getChainId()`
because, its have upgrade new starknet version such as 3.6.0

2024-12-24 09:53 UTC, michojekunle commented
> > > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > > 
> > > 
> > > U can take a look : useTargetNetwork to resolve
> > 
> > Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> > 
> > What could be the issue or am I missing something
> 
> yes, that why we need to update carefully, so u can tracking chain ID by
> `const chainId = await provider.provider.getChainId()`
> because, its have upgrade new starknet version such as 3.6.0

Alright thanks for this will try this out now

2024-12-24 10:14 UTC, Buuh2511 commented
> > > > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > > > 
> > > > 
> > > > U can take a look : useTargetNetwork to resolve
> > > 
> > > 
> > > Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> > > What could be the issue or am I missing something
> > 
> > 
> > yes, that why we need to update carefully, so u can tracking chain ID by
> > `const chainId = await provider.provider.getChainId()`
> > because, its have upgrade new starknet version such as 3.6.0
> 
> Alright thanks for this will try this out now

make sure u do a compare something like this. constants take from starknet
![Screenshot 2024-12-24 at 5 13 06 PM](https://github.com/user-attachments/assets/5c30df1b-221b-4766-abd5-7792b59fb7f7)

2024-12-24 10:32 UTC, michojekunle commented
> > > > > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > > > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > > > > 
> > > > > 
> > > > > U can take a look : useTargetNetwork to resolve
> > > > 
> > > > 
> > > > Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> > > > What could be the issue or am I missing something
> > > 
> > > 
> > > yes, that why we need to update carefully, so u can tracking chain ID by
> > > `const chainId = await provider.provider.getChainId()`
> > > because, its have upgrade new starknet version such as 3.6.0
> > 
> > Alright thanks for this will try this out now
> 
> make sure u do a compare something like this. constants take from starknet
> ![Screenshot 2024-12-24 at 5 13 06 PM](https://github.com/user-attachments/assets/5c30df1b-221b-4766-abd5-7792b59fb7f7)
> 

Thank you so much for this it worked, I've committed changes now, please review

2024-12-24 10:39 UTC, Buuh2511 commented
> > > > > > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > > > > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > > > > > 
> > > > > > 
> > > > > > U can take a look : useTargetNetwork to resolve
> > > > > 
> > > > > 
> > > > > Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> > > > > What could be the issue or am I missing something
> > > > 
> > > > 
> > > > yes, that why we need to update carefully, so u can tracking chain ID by
> > > > `const chainId = await provider.provider.getChainId()`
> > > > because, its have upgrade new starknet version such as 3.6.0
> > > 
> > > 
> > > Alright thanks for this will try this out now
> > 
> > 
> > make sure u do a compare something like this. constants take from starknet
> > ![Screenshot 2024-12-24 at 5 13 06 PM](https://private-user-images.githubusercontent.com/57097047/398388750-5c30df1b-221b-4766-abd5-7792b59fb7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzY4NjIsIm5iZiI6MTczNTAzNjU2MiwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzODg3NTAtNWMzMGRmMWItMjIxYi00NzY2LWFiZDUtNzc5MmI1OWZiN2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwMzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYWU0M2U3ZjkzMTJmMzU3NzgyYzVkYTMyYjk2M2UyZTI4OWRmZGUyNzUxNjZiNjk5YWI0MTAzYjlmNGZjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q0NsJP2vU69U-oEZTpjWlmlz33ZKewtc_Bpu7ExFhSw)
> 
> Thank you so much for this it worked, I've committed changes now, please review

Have all the other bugs above been fixed?

2024-12-24 10:43 UTC, michojekunle commented
> > > > > > > > @Buuh2511 Please review the only thing left now is the Wrong Network thingy, still haven't gotten where the issue comes from, but every other thing has been fixed
> > > > > > > > Please can also help look into it @Buuh2511 @gianalarcon and suggest possible ways to fix 🥲
> > > > > > > 
> > > > > > > 
> > > > > > > U can take a look : useTargetNetwork to resolve
> > > > > > 
> > > > > > 
> > > > > > Based on this the issue I have is that no matter the network that is currently connected to the dapp the usetargetnetwork works and returns what is specified in the target networks but the use account (getting the chainid of the currently connected account is not returning the chainId of the currently connected chain but the id of the target network.
> > > > > > What could be the issue or am I missing something
> > > > > 
> > > > > 
> > > > > yes, that why we need to update carefully, so u can tracking chain ID by
> > > > > `const chainId = await provider.provider.getChainId()`
> > > > > because, its have upgrade new starknet version such as 3.6.0
> > > > 
> > > > 
> > > > Alright thanks for this will try this out now
> > > 
> > > 
> > > make sure u do a compare something like this. constants take from starknet
> > > ![Screenshot 2024-12-24 at 5 13 06 PM](https://private-user-images.githubusercontent.com/57097047/398388750-5c30df1b-221b-4766-abd5-7792b59fb7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzY4NjIsIm5iZiI6MTczNTAzNjU2MiwicGF0aCI6Ii81NzA5NzA0Ny8zOTgzODg3NTAtNWMzMGRmMWItMjIxYi00NzY2LWFiZDUtNzc5MmI1OWZiN2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEwMzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYWU0M2U3ZjkzMTJmMzU3NzgyYzVkYTMyYjk2M2UyZTI4OWRmZGUyNzUxNjZiNjk5YWI0MTAzYjlmNGZjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q0NsJP2vU69U-oEZTpjWlmlz33ZKewtc_Bpu7ExFhSw)
> > 
> > Thank you so much for this it worked, I've committed changes now, please review
> 
> Have all the other bugs above been fixed?

Yes

2024-12-24 10:46 UTC, Buuh2511 commented
still not getting wrong network after reloading page and connected to wrong network
Wrong UI, the spacing still havent fixed
![Screenshot 2024-12-24 at 5 44 46 PM](https://github.com/user-attachments/assets/df8dd8c8-d2b0-4127-8561-994d7fa3a10a)

2024-12-24 10:55 UTC, michojekunle commented
> still not getting wrong network after reloading page and connected to wrong network
> Wrong UI, the spacing still havent fixed
> ![Screenshot 2024-12-24 at 5 44 46 PM](https://github.com/user-attachments/assets/df8dd8c8-d2b0-4127-8561-994d7fa3a10a)
> 
On it now

2024-12-24 12:40 UTC, michojekunle commented
Hi @Buuh2511 I've fixed the spacing issue and the share referral code modal wrong UI 

For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?

2024-12-24 13:58 UTC, michojekunle commented
> Hi @Buuh2511 I've fixed the spacing issue and the share referral code modal wrong UI
> 
> For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?

@gianalarcon

2024-12-24 14:50 UTC, gianalarcon commented
> > Hi @Buuh2511 I've fixed the spacing issue and the share referral code modal wrong UI
> > For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?
> 
> @gianalarcon

Buu will check on few hours, dont worry man, this issue is kind of hard

2024-12-24 15:42 UTC, Buuh2511 commented
> For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?

Im not ready to do deep debugging, however you can try using useAutoConnect to ensure connection and chainId every time the page refreshes

2024-12-24 16:11 UTC, michojekunle commented
> > For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?
> 
> Can u try using useAutoConnect to ensure connection and chainId every time the page refreshes

Okay I'm currently using useAutoConnect in the index page of the ConnectModal it's still the same error

2024-12-24 16:54 UTC, Buuh2511 commented
> > > For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?
> > 
> > 
> > Can u try using useAutoConnect to ensure connection and chainId every time the page refreshes
> 
> Okay I'm currently using useAutoConnect in the index page of the CustomConnectButton it's still the same error

Can u try to store chainId  into storage at the frist time connect to wallet and anytime switch network, try to take this variable to compare to chainId from targetNetwork

2024-12-24 16:59 UTC, michojekunle commented
> > > > For the wrong network dropdown, it's the same error I was getting before hand with the useAccount hook, now using useProvider, what other methods can be used, I've been looking up starknetjs and SNIPs to implement fetching the currently connected chainId at anytime including when the page is reloaded, what do you think?
> > > 
> > > 
> > > Can u try using useAutoConnect to ensure connection and chainId every time the page refreshes
> > 
> > 
> > Okay I'm currently using useAutoConnect in the index page of the CustomConnectButton it's still the same error
> 
> Can u try to store chainId into storage at the frist time connect to wallet and anytime switch network, try to take this variable to compare to chainId from targetNetwork

Alright would try this now

2024-12-25 05:15 UTC, michojekunle commented
Hi @Buuh2511 @gianalarcon ,

I've implemented persistency for the `chainId` using `localStorage`. However, I’m facing an issue with listening properly for chain switch events to update the `chainId` stored in `localStorage`.

- I tried using a `useEffect` with `account` and `provider` as dependencies.
- The issue is that these dependencies don’t always give the correct `chainId` on the initial page load.
- This can result in misleading updates to the `chainId` in `localStorage`.

The goal is to reliably detect chain switches and ensure `localStorage` is updated with the correct `chainId`. Any ideas or suggestions on how to implement this effectively?

2024-12-25 23:16 UTC, michojekunle commented
Hi @Buuh2511 @gianalarcon Merry Christmas 🤩🥳

I've finally fixed the bug, please review

2024-12-26 03:06 UTC, Buuh2511 commented
can u make this text as a text-center
<img width="1121" alt="Screenshot 2024-12-26 at 9 53 31 AM" src="https://github.com/user-attachments/assets/e9a0c746-1ae0-49ff-9dc2-b0270f745601" />

When you are not logged in, this line will appear. Once you are logged in, this line will disappear
<img width="2235" alt="Screenshot 2024-12-26 at 9 56 10 AM" src="https://github.com/user-attachments/assets/2b1781f4-63ef-4d4a-afd6-18ecc34e8844" />

cant get balance although connect correct network
<img width="2226" alt="Screenshot 2024-12-26 at 9 59 38 AM" src="https://github.com/user-attachments/assets/800aa80d-6c1a-4c15-8761-49ee187957e4" />

try to open this when connect wrong network
<img width="2170" alt="Screenshot 2024-12-26 at 10 05 06 AM" src="https://github.com/user-attachments/assets/141f4ed4-ad95-467d-97b5-cf3b688eea0d" />

2024-12-26 05:58 UTC, michojekunle commented
> can u make this text as a text-center <img alt="Screenshot 2024-12-26 at 9 53 31 AM" width="1121" src="https://private-user-images.githubusercontent.com/57097047/398622507-e9a0c746-1ae0-49ff-9dc2-b0270f745601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI1MDctZTlhMGM3NDYtMWFlMC00OWZmLTlkYzItYjAyNzBmNzQ1NjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjQ3MTJjM2YzYTE0MzI3YTkzMmM3M2E1NzZlNjYyZWIxY2Q5MDY3Yjc0OWUzOTEwMzFlYzIwYjdiNzY3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.llTPvp_4HCsXKf9qId8qhkBBBNz1oWF96ofZGaUTghY">
> 
> When you are not logged in, this line will appear. Once you are logged in, this line will disappear <img alt="Screenshot 2024-12-26 at 9 56 10 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398622601-2b1781f4-63ef-4d4a-afd6-18ecc34e8844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI2MDEtMmIxNzgxZjQtNjNlZi00ZDRhLWFmZDYtMThlY2MzNGU4ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZGI2ZTMxZTA1NmQ2MTMzYTBiNWFiOGY2NzZlYzJmZmVkMGNlYzI1N2ZjM2M5OGMwMjczNTZkMDA0OGRhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgKvXNPP9MQSEzBmb4rvK19OUtMjt-9Z7hEIYvlYXWk">
> 
> cant get balance although connect correct network <img alt="Screenshot 2024-12-26 at 9 59 38 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623383-800aa80d-6c1a-4c15-8761-49ee187957e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjMzODMtODAwYWE4MGQtNmMxYS00YzE1LTg3NjEtNDllZTE4Nzk1N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmE3MmM5MGI2MTZmMGE5OGM3ZDU2NzliMjI2NTYwY2YwOTNhNGU3ZWYyZjRjMDk5MGE2MWEyMmEyZmI3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8FPwiRTGYOX2904VR9wUhbFrKLID27ucrxjWML7Lh4">
> 
> try to open this when connect wrong network <img alt="Screenshot 2024-12-26 at 10 05 06 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623621-141f4ed4-ad95-467d-97b5-cf3b688eea0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjM2MjEtMTQxZjRlZDQtYWQ5NS00NjdkLTk3YjUtY2YzYjY4OGVlYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWI1NGFmNjM4ZmNlNDRhNDkwN2RlYmE0NGQxODFmZWU3M2Y2ODM1Nzk5ZGNlNDdkNWRkNDc2Y2QzZjQ4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUK05S_CoKQcDpuKqd0zc-HUPbnS9rIlhA1Idz0dCfs">

Alright on it now Gm

2024-12-26 06:04 UTC, michojekunle commented
> > can u make this text as a text-center <img alt="Screenshot 2024-12-26 at 9 53 31 AM" width="1121" src="https://private-user-images.githubusercontent.com/57097047/398622507-e9a0c746-1ae0-49ff-9dc2-b0270f745601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI1MDctZTlhMGM3NDYtMWFlMC00OWZmLTlkYzItYjAyNzBmNzQ1NjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjQ3MTJjM2YzYTE0MzI3YTkzMmM3M2E1NzZlNjYyZWIxY2Q5MDY3Yjc0OWUzOTEwMzFlYzIwYjdiNzY3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.llTPvp_4HCsXKf9qId8qhkBBBNz1oWF96ofZGaUTghY">
> > When you are not logged in, this line will appear. Once you are logged in, this line will disappear <img alt="Screenshot 2024-12-26 at 9 56 10 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398622601-2b1781f4-63ef-4d4a-afd6-18ecc34e8844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI2MDEtMmIxNzgxZjQtNjNlZi00ZDRhLWFmZDYtMThlY2MzNGU4ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZGI2ZTMxZTA1NmQ2MTMzYTBiNWFiOGY2NzZlYzJmZmVkMGNlYzI1N2ZjM2M5OGMwMjczNTZkMDA0OGRhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgKvXNPP9MQSEzBmb4rvK19OUtMjt-9Z7hEIYvlYXWk">
> > cant get balance although connect correct network <img alt="Screenshot 2024-12-26 at 9 59 38 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623383-800aa80d-6c1a-4c15-8761-49ee187957e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjMzODMtODAwYWE4MGQtNmMxYS00YzE1LTg3NjEtNDllZTE4Nzk1N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmE3MmM5MGI2MTZmMGE5OGM3ZDU2NzliMjI2NTYwY2YwOTNhNGU3ZWYyZjRjMDk5MGE2MWEyMmEyZmI3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8FPwiRTGYOX2904VR9wUhbFrKLID27ucrxjWML7Lh4">
> > try to open this when connect wrong network <img alt="Screenshot 2024-12-26 at 10 05 06 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623621-141f4ed4-ad95-467d-97b5-cf3b688eea0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjM2MjEtMTQxZjRlZDQtYWQ5NS00NjdkLTk3YjUtY2YzYjY4OGVlYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWI1NGFmNjM4ZmNlNDRhNDkwN2RlYmE0NGQxODFmZWU3M2Y2ODM1Nzk5ZGNlNDdkNWRkNDc2Y2QzZjQ4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUK05S_CoKQcDpuKqd0zc-HUPbnS9rIlhA1Idz0dCfs">
> 
> Alright on it now Gm

@Buuh2511 is there a component for this wrong connect modal error when connected to the wrong network or I'd create the component

2024-12-26 06:38 UTC, Buuh2511 commented
> > > can u make this text as a text-center <img alt="Screenshot 2024-12-26 at 9 53 31 AM" width="1121" src="https://private-user-images.githubusercontent.com/57097047/398622507-e9a0c746-1ae0-49ff-9dc2-b0270f745601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI1MDctZTlhMGM3NDYtMWFlMC00OWZmLTlkYzItYjAyNzBmNzQ1NjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjQ3MTJjM2YzYTE0MzI3YTkzMmM3M2E1NzZlNjYyZWIxY2Q5MDY3Yjc0OWUzOTEwMzFlYzIwYjdiNzY3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.llTPvp_4HCsXKf9qId8qhkBBBNz1oWF96ofZGaUTghY">
> > > When you are not logged in, this line will appear. Once you are logged in, this line will disappear <img alt="Screenshot 2024-12-26 at 9 56 10 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398622601-2b1781f4-63ef-4d4a-afd6-18ecc34e8844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI2MDEtMmIxNzgxZjQtNjNlZi00ZDRhLWFmZDYtMThlY2MzNGU4ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZGI2ZTMxZTA1NmQ2MTMzYTBiNWFiOGY2NzZlYzJmZmVkMGNlYzI1N2ZjM2M5OGMwMjczNTZkMDA0OGRhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgKvXNPP9MQSEzBmb4rvK19OUtMjt-9Z7hEIYvlYXWk">
> > > cant get balance although connect correct network <img alt="Screenshot 2024-12-26 at 9 59 38 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623383-800aa80d-6c1a-4c15-8761-49ee187957e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjMzODMtODAwYWE4MGQtNmMxYS00YzE1LTg3NjEtNDllZTE4Nzk1N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmE3MmM5MGI2MTZmMGE5OGM3ZDU2NzliMjI2NTYwY2YwOTNhNGU3ZWYyZjRjMDk5MGE2MWEyMmEyZmI3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8FPwiRTGYOX2904VR9wUhbFrKLID27ucrxjWML7Lh4">
> > > try to open this when connect wrong network <img alt="Screenshot 2024-12-26 at 10 05 06 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623621-141f4ed4-ad95-467d-97b5-cf3b688eea0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjM2MjEtMTQxZjRlZDQtYWQ5NS00NjdkLTk3YjUtY2YzYjY4OGVlYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWI1NGFmNjM4ZmNlNDRhNDkwN2RlYmE0NGQxODFmZWU3M2Y2ODM1Nzk5ZGNlNDdkNWRkNDc2Y2QzZjQ4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUK05S_CoKQcDpuKqd0zc-HUPbnS9rIlhA1Idz0dCfs">
> > 
> > 
> > Alright on it now Gm
> 
> @Buuh2511 is there a component for this wrong connect modal error when connected to the wrong network or I'd create the component

GM, It's already there, u can find it

2024-12-26 06:42 UTC, michojekunle commented
> > > > can u make this text as a text-center <img alt="Screenshot 2024-12-26 at 9 53 31 AM" width="1121" src="https://private-user-images.githubusercontent.com/57097047/398622507-e9a0c746-1ae0-49ff-9dc2-b0270f745601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI1MDctZTlhMGM3NDYtMWFlMC00OWZmLTlkYzItYjAyNzBmNzQ1NjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjQ3MTJjM2YzYTE0MzI3YTkzMmM3M2E1NzZlNjYyZWIxY2Q5MDY3Yjc0OWUzOTEwMzFlYzIwYjdiNzY3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.llTPvp_4HCsXKf9qId8qhkBBBNz1oWF96ofZGaUTghY">
> > > > When you are not logged in, this line will appear. Once you are logged in, this line will disappear <img alt="Screenshot 2024-12-26 at 9 56 10 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398622601-2b1781f4-63ef-4d4a-afd6-18ecc34e8844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjI2MDEtMmIxNzgxZjQtNjNlZi00ZDRhLWFmZDYtMThlY2MzNGU4ODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZGI2ZTMxZTA1NmQ2MTMzYTBiNWFiOGY2NzZlYzJmZmVkMGNlYzI1N2ZjM2M5OGMwMjczNTZkMDA0OGRhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VgKvXNPP9MQSEzBmb4rvK19OUtMjt-9Z7hEIYvlYXWk">
> > > > cant get balance although connect correct network <img alt="Screenshot 2024-12-26 at 9 59 38 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623383-800aa80d-6c1a-4c15-8761-49ee187957e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjMzODMtODAwYWE4MGQtNmMxYS00YzE1LTg3NjEtNDllZTE4Nzk1N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmE3MmM5MGI2MTZmMGE5OGM3ZDU2NzliMjI2NTYwY2YwOTNhNGU3ZWYyZjRjMDk5MGE2MWEyMmEyZmI3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8FPwiRTGYOX2904VR9wUhbFrKLID27ucrxjWML7Lh4">
> > > > try to open this when connect wrong network <img alt="Screenshot 2024-12-26 at 10 05 06 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398623621-141f4ed4-ad95-467d-97b5-cf3b688eea0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTI2OTYsIm5iZiI6MTczNTE5MjM5NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg2MjM2MjEtMTQxZjRlZDQtYWQ5NS00NjdkLTk3YjUtY2YzYjY4OGVlYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA1NTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWI1NGFmNjM4ZmNlNDRhNDkwN2RlYmE0NGQxODFmZWU3M2Y2ODM1Nzk5ZGNlNDdkNWRkNDc2Y2QzZjQ4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HUK05S_CoKQcDpuKqd0zc-HUPbnS9rIlhA1Idz0dCfs">
> > > 
> > > 
> > > Alright on it now Gm
> > 
> > 
> > @Buuh2511 is there a component for this wrong connect modal error when connected to the wrong network or I'd create the component
> 
> GM, It's already there, u can find it

Yes, found it already in the notification component

2024-12-26 09:19 UTC, michojekunle commented
Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance
![image](https://github.com/user-attachments/assets/fe6ec291-02de-40b4-ad04-049de4a51fed)

2024-12-26 09:20 UTC, michojekunle commented
Also @Buuh2511 

I've made other changes Please review

2024-12-26 09:22 UTC, Buuh2511 commented
> Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)

so, can u do a Spinner when cant get balance, but just for error code 429

2024-12-26 09:23 UTC, michojekunle commented
> > Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)
> 
> so, can u do a Spinner when cant get balance, but just for error code 429
> 

Alright on it now

2024-12-26 09:27 UTC, Buuh2511 commented
> > > Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)
> > 
> > 
> > so, can u do a Spinner when cant get balance, but just for error code 429
> 
> Alright on it now

u are nealy complete this PR, so make sure every thing work well as expect [The Marquis](https://themarquis.xyz/)
cuz there is version 1, i will availabe for this PR in 6hours, still that time just play around and do some deep test

2024-12-26 10:39 UTC, michojekunle commented
> > > > Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)
> > > 
> > > 
> > > so, can u do a Spinner when cant get balance, but just for error code 429
> > 
> > 
> > Alright on it now
> 
> u are nealy complete this PR, so make sure every thing work well as expect [The Marquis](https://themarquis.xyz/) cuz there is version 1, i will availabe for this PR in 6hours, still that time just play around and do some deep test

Alright sure

2024-12-26 10:43 UTC, michojekunle commented
> > Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)
> 
> so, can u do a Spinner when cant get balance, but just for error code 429

So I thought of another scenario to implement this since the hooks are using the useDeployedContractInfo hook which is maing a request to get the address, classHash, and abi of eth or strk everytime why don't I implement a fallback; constants: the eth and strk contract addresses and abi's,  that what i implemented now and it works fine now.

2024-12-26 10:44 UTC, michojekunle commented
> > > > > Hi @Buuh2511 the reason for this is cause of the way the balance is being fetched using nethermind free rpc, when there are too many request there is an error and then the balance is not fetched and is not reflected on the page, from the use of the useScaffoldStrkBalance and useScaffoldEthBalance ![image](https://private-user-images.githubusercontent.com/90222287/398681655-fe6ec291-02de-40b4-ad04-049de4a51fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDUwODcsIm5iZiI6MTczNTIwNDc4NywicGF0aCI6Ii85MDIyMjI4Ny8zOTg2ODE2NTUtZmU2ZWMyOTEtMDJkZS00MGI0LWFkMDQtMDQ5ZGU0YTUxZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTdhYmQxNjMzN2E0MTc3MDdhN2E1NGU3MGYyNmEzOTcyNjRlMWYzNGQ3NDBhNTIxMjQ1OTJmMjUyZDNmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G-sD7As8rqILuXFe78hu2M7kZAp8W7uHe168q4Gy5rw)
> > > > 
> > > > 
> > > > so, can u do a Spinner when cant get balance, but just for error code 429
> > > 
> > > 
> > > Alright on it now
> > 
> > 
> > u are nealy complete this PR, so make sure every thing work well as expect [The Marquis](https://themarquis.xyz/) cuz there is version 1, i will availabe for this PR in 6hours, still that time just play around and do some deep test
> 
> Alright sure

I'll now move on to doing the overall deep testing btw I haven't signed up yet cause I don't have a referral code so I just test by always commenting the protected routes locally from the middleware.

can you share a referral code to sign up to test?

2024-12-26 10:45 UTC, gianalarcon commented
referral codes: 
OPBDFRSU
J3KE0YMR

@michojekunle

2024-12-26 10:48 UTC, michojekunle commented
> referral codes: OPBDFRSU J3KE0YMR
> 
> @michojekunle

Thank you ser

2024-12-26 11:40 UTC, michojekunle commented
Hi @gianalarcon It just seems like I'm stuck here i think it's the api production uri I'm missing from the env  

![image](https://github.com/user-attachments/assets/254c2a82-18b1-4386-97e8-1b683ce18940)

2024-12-26 12:49 UTC, gianalarcon commented
DM on discord pls https://discord.gg/bWuQFHHA

2024-12-26 13:16 UTC, michojekunle commented
> DM on discord pls https://discord.gg/bWuQFHHA

Alright

2024-12-26 15:50 UTC, Buuh2511 commented
- Put text as a text-center here pls
![image](https://github.com/user-attachments/assets/254a17ed-06bf-4a9a-9fbf-54632ef6ee8e)

- It will take a short while to see the balance, it is going from 0 to ...STRK, during this time do loading as a Spiner

Then, everything is working for now, I will check more round in morning tomorrow

2024-12-26 16:39 UTC, Buuh2511 commented
> * Put text as a text-center here pls
>   ![image](https://private-user-images.githubusercontent.com/57097047/398759842-254a17ed-06bf-4a9a-9fbf-54632ef6ee8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzEzNzYsIm5iZiI6MTczNTIzMTA3NiwicGF0aCI6Ii81NzA5NzA0Ny8zOTg3NTk4NDItMjU0YTE3ZWQtMDZiZi00YTlhLTlmYmYtNTQ2MzJlZjZlZThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDE2Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNDEwOTEyODk3YjU0OWUxNjdiNTFhOTk0OTU5ZTllYzYyOTczYjRlNjY1NGFiOTY2MjUyMmUwNzRhZDU3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1LgS-fyYqEegQSDTM0C6L6BbAdeIL2WgBrREE7VAwak)
> * It will take a short while to see the balance, it is going from 0 to ...STRK, during this time do loading as a Spiner
> 
> Then, everything is working for now, I will check more round in morning tomorrow

> It will take a short while to see the balance, it is going from 0 to ...STRK, during this time do loading as a Spiner
Also need to implement for Select Token Modal

2024-12-26 19:02 UTC, michojekunle commented
Hi @Buuh2511 

I've now added in both pages (deposit and withdrawal) and the select token modal the loading spinner while fetching token balances

Please review

2024-12-27 03:17 UTC, Buuh2511 commented
Spiner just keep loading, cant get balance in somtime
<img width="1119" alt="Screenshot 2024-12-27 at 10 03 36 AM" src="https://github.com/user-attachments/assets/5ecc3d2a-a4b1-4ee7-80de-7512c7a60405" />

Need to fix alignment
<img width="702" alt="Screenshot 2024-12-27 at 10 04 01 AM" src="https://github.com/user-attachments/assets/343e9d98-bb85-4bff-b807-a99a4780e726" />

When try to connect wallet without extensions going got bug
<img width="2231" alt="Screenshot 2024-12-27 at 10 06 47 AM" src="https://github.com/user-attachments/assets/c8c5bb69-2974-4f8f-b1dc-ed2b4b8d56a2" />

Got an error when try to connect wallet but still havent connected yet at the first time launch app
<img width="2210" alt="Screenshot 2024-12-27 at 10 15 51 AM" src="https://github.com/user-attachments/assets/80c65c5f-c024-4aae-ba2b-d3115c021d0c" />

2024-12-27 09:40 UTC, michojekunle commented
> Spiner just keep loading, cant get balance in somtime <img alt="Screenshot 2024-12-27 at 10 03 36 AM" width="1119" src="https://private-user-images.githubusercontent.com/57097047/398835738-5ecc3d2a-a4b1-4ee7-80de-7512c7a60405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODc3NjAsIm5iZiI6MTczNTI4NzQ2MCwicGF0aCI6Ii81NzA5NzA0Ny8zOTg4MzU3MzgtNWVjYzNkMmEtYTRiMS00ZWU3LTgwZGUtNzUxMmM3YTYwNDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODQxNDBlNjA2MWFlZjViOTc2ZGI4YTUzN2U1OWIwNzVkNjIxMjQ1MjFlYjA2OGI4Yzk0Y2ZkYzY4NzFiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UKsDi9C82qJlPGEVLs1yoQ7ww-ChqJDYan4Z1XiYmB4">
> 
> Need to fix alignment <img alt="Screenshot 2024-12-27 at 10 04 01 AM" width="702" src="https://private-user-images.githubusercontent.com/57097047/398835837-343e9d98-bb85-4bff-b807-a99a4780e726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODc3NjAsIm5iZiI6MTczNTI4NzQ2MCwicGF0aCI6Ii81NzA5NzA0Ny8zOTg4MzU4MzctMzQzZTlkOTgtYmI4NS00YmZmLWI4MDctYTk5YTQ3ODBlNzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTQ2YjUyODFiMzgxMDUzYzUxZGMxNmM0NTBkYWQ1NTM5ZjdmNDczMTY3ZGI2M2I5MTA0ZTkxN2QxMzFkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._MdMtx2XSwZITCU63wWkFUdv4rfCEw-8E4Fq-PrQkQc">
> 
> When try to connect wallet without extensions going got bug <img alt="Screenshot 2024-12-27 at 10 06 47 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398835861-c8c5bb69-2974-4f8f-b1dc-ed2b4b8d56a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODc3NjAsIm5iZiI6MTczNTI4NzQ2MCwicGF0aCI6Ii81NzA5NzA0Ny8zOTg4MzU4NjEtYzhjNWJiNjktMjk3NC00ZjhmLWIxZGMtZWQyYjRiOGQ1NmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTM2MmY2MDQ0OTI1ZDgxZDVkZjFmZjk4MzAyNDgzZmU5ODVlZjgyNzM2MTAwMjlmMmIwMWI0MzA4NGY0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p8zomwCWpA7LQY8ScaYW4KbNzow1zixLlrvLzwMCvPQ">
> 
> Got an error when try to connect wallet but still havent connected yet at the first time launch app <img alt="Screenshot 2024-12-27 at 10 15 51 AM" width="2000" src="https://private-user-images.githubusercontent.com/57097047/398836880-80c65c5f-c024-4aae-ba2b-d3115c021d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODc3NjAsIm5iZiI6MTczNTI4NzQ2MCwicGF0aCI6Ii81NzA5NzA0Ny8zOTg4MzY4ODAtODBjNjVjNWYtYzAyNC00YWFlLWJhMmItZDMxMTVjMDIxZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNzQ2YjdhNzc4ZjkxNDBmYjkyYTQ5YTQyODNiYjA3ZWFkODBhNTk1YzJhZWE1NmEzZTUyZmU0MTEwYzQ1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XG2tu45Q4hH38b3r6NafaX8ZI7I6YUHlEjnH3EOWRLw">

For the loading spinner it's only when I'm not connected that it keeps showing spinning or whether there's an error fetching the balance it shows the spinning 

here first cause my wallet is not connected yet 
PS: I refreshed the page 

![image](https://github.com/user-attachments/assets/bbe70cd5-971a-4f06-b1eb-8a5a915297d4)

And then here where my wallet is now reflected as connected after complete page load and I'm not logged in so my marquis balance keeps spinning cause of the error fetching my balance
![image](https://github.com/user-attachments/assets/eca6dc9d-6746-46f8-b76d-03e9c29ec8d8)

- Fixed the last two bugs 

- Fixed this alignment also 
![image](https://github.com/user-attachments/assets/c4317993-e40b-448e-aeff-13d0e1e85020)

2024-12-27 09:41 UTC, michojekunle commented
Hi, Gm @Buuh2511 

Please review

2024-12-28 07:33 UTC, Buuh2511 commented
- got this error when try to connect walllet without extension
![image](https://github.com/user-attachments/assets/bb46492b-058f-4dbc-adfc-ea579416789c)

- "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux 
- Cant close modal when click on left and right of screen, only close when click on top and bottom of screen
![image](https://github.com/user-attachments/assets/6f41da56-75d6-4391-8a29-e7ae16a819bd)

2024-12-28 09:24 UTC, michojekunle commented
> * got this error when try to connect walllet without extension
>   ![image](https://private-user-images.githubusercontent.com/57097047/399058261-bb46492b-058f-4dbc-adfc-ea579416789c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTgyNjEtYmI0NjQ5MmItMDU4Zi00ZGJjLWFkZmMtZWE1Nzk0MTY3ODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjdmMWRhODQwYWM4OGQwMDEzOWU5MDFjZTE2NWYzZDljMDc4NzU5Y2FkMGRjOWZmMzNhYTljMDg4YjcwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_6dpXsA0F3kmjja8X52dZZjMOoRb3xZdg90NYKxk1E)
> * "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> * Cant close modal when click on left and right of screen, only close when click on top and bottom of screen
>   ![image](https://private-user-images.githubusercontent.com/57097047/399059342-6f41da56-75d6-4391-8a29-e7ae16a819bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTkzNDItNmY0MWRhNTYtNzVkNi00MzkxLThhMjktZTdhZTE2YTgxOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGI1NzliMWNmNzE3MTlhMzEyODFhZDU3N2QwN2Q4NDc3ZThjYmNiNzA5ZTZmOGU3OWJjMGQ3YThmYjM0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tdd7yGc7VfY4MjujMWAsJjnxrtwiLZ9Mdut0hnisUC0)

- The first error means that the wallet is not installed in the current user browser that is the connector (argent or braavos) is not found 

- yes the connection is kept, it just takes a little time to restore the connection locally nextjs dev server loading speed

- Alright will look into this last error now for the modal

2024-12-28 09:47 UTC, Buuh2511 commented
> > * got this error when try to connect walllet without extension
> >   ![image](https://private-user-images.githubusercontent.com/57097047/399058261-bb46492b-058f-4dbc-adfc-ea579416789c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTgyNjEtYmI0NjQ5MmItMDU4Zi00ZGJjLWFkZmMtZWE1Nzk0MTY3ODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjdmMWRhODQwYWM4OGQwMDEzOWU5MDFjZTE2NWYzZDljMDc4NzU5Y2FkMGRjOWZmMzNhYTljMDg4YjcwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_6dpXsA0F3kmjja8X52dZZjMOoRb3xZdg90NYKxk1E)
> > * "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> > * Cant close modal when click on left and right of screen, only close when click on top and bottom of screen
> >   ![image](https://private-user-images.githubusercontent.com/57097047/399059342-6f41da56-75d6-4391-8a29-e7ae16a819bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTkzNDItNmY0MWRhNTYtNzVkNi00MzkxLThhMjktZTdhZTE2YTgxOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGI1NzliMWNmNzE3MTlhMzEyODFhZDU3N2QwN2Q4NDc3ZThjYmNiNzA5ZTZmOGU3OWJjMGQ3YThmYjM0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tdd7yGc7VfY4MjujMWAsJjnxrtwiLZ9Mdut0hnisUC0)
> 
> Alright Gm @Buuh2511
> 
> * So, the first error means that the wallet is not installed in the current user browser that is the connector (argent or braavos) is not found
> * yes the connection is kept, it just takes a little time to restore the connection locally nextjs dev server loading speed
> * Alright will look into this last error now for the modal

i mean when switch between deposit and withdraw page, connection should be kepth

2024-12-28 09:49 UTC, michojekunle commented
> > > * got this error when try to connect walllet without extension
> > >   ![image](https://private-user-images.githubusercontent.com/57097047/399058261-bb46492b-058f-4dbc-adfc-ea579416789c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTgyNjEtYmI0NjQ5MmItMDU4Zi00ZGJjLWFkZmMtZWE1Nzk0MTY3ODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjdmMWRhODQwYWM4OGQwMDEzOWU5MDFjZTE2NWYzZDljMDc4NzU5Y2FkMGRjOWZmMzNhYTljMDg4YjcwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_6dpXsA0F3kmjja8X52dZZjMOoRb3xZdg90NYKxk1E)
> > > * "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> > > * Cant close modal when click on left and right of screen, only close when click on top and bottom of screen
> > >   ![image](https://private-user-images.githubusercontent.com/57097047/399059342-6f41da56-75d6-4391-8a29-e7ae16a819bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTkzNDItNmY0MWRhNTYtNzVkNi00MzkxLThhMjktZTdhZTE2YTgxOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGI1NzliMWNmNzE3MTlhMzEyODFhZDU3N2QwN2Q4NDc3ZThjYmNiNzA5ZTZmOGU3OWJjMGQ3YThmYjM0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tdd7yGc7VfY4MjujMWAsJjnxrtwiLZ9Mdut0hnisUC0)
> > 
> > Alright Gm @Buuh2511
> > 
> > * So, the first error means that the wallet is not installed in the current user browser that is the connector (argent or braavos) is not found
> > * yes the connection is kept, it just takes a little time to restore the connection locally nextjs dev server loading speed
> > * Alright will look into this last error now for the modal
> 
> "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> i mean when switch between deposit and withdraw page, connection should be kepth

Alright will look into this too

2024-12-28 09:50 UTC, michojekunle commented
> > > * got this error when try to connect walllet without extension
> > >   ![image](https://private-user-images.githubusercontent.com/57097047/399058261-bb46492b-058f-4dbc-adfc-ea579416789c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTgyNjEtYmI0NjQ5MmItMDU4Zi00ZGJjLWFkZmMtZWE1Nzk0MTY3ODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMjdmMWRhODQwYWM4OGQwMDEzOWU5MDFjZTE2NWYzZDljMDc4NzU5Y2FkMGRjOWZmMzNhYTljMDg4YjcwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n_6dpXsA0F3kmjja8X52dZZjMOoRb3xZdg90NYKxk1E)
> > > * "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> > > * Cant close modal when click on left and right of screen, only close when click on top and bottom of screen
> > >   ![image](https://private-user-images.githubusercontent.com/57097047/399059342-6f41da56-75d6-4391-8a29-e7ae16a819bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzc4OTgsIm5iZiI6MTczNTM3NzU5OCwicGF0aCI6Ii81NzA5NzA0Ny8zOTkwNTkzNDItNmY0MWRhNTYtNzVkNi00MzkxLThhMjktZTdhZTE2YTgxOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGI1NzliMWNmNzE3MTlhMzEyODFhZDU3N2QwN2Q4NDc3ZThjYmNiNzA5ZTZmOGU3OWJjMGQ3YThmYjM0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tdd7yGc7VfY4MjujMWAsJjnxrtwiLZ9Mdut0hnisUC0)
> > 
> > Alright Gm @Buuh2511
> > 
> > * So, the first error means that the wallet is not installed in the current user browser that is the connector (argent or braavos) is not found
> > * yes the connection is kept, it just takes a little time to restore the connection locally nextjs dev server loading speed
> > * Alright will look into this last error now for the modal
> 
> "PS: I refreshed the page" : so, we need to keep connection after reload page, better ux
> i mean when switch between deposit and withdraw page, connection should be kepth

Alright will look into this too

2024-12-28 12:14 UTC, michojekunle commented
Hi @Buuh2511

-  I think the wallet connection kept works well with braavos wallet, this only comes up with argent wallet in this case any time the dapp wants to reestablish a connection to argent wallet it prompts users to reenter their passwords to unlock their argent wallet and I read about that in this issue https://github.com/starknet-io/get-starknet/issues/192, which a user will most likely reject there and when the wallet is locked the dapp cannot reestablish connection with the dapp

2024-12-30 03:24 UTC, Buuh2511 commented
Many thanks for your contribution ! @michojekunle

2024-12-30 03:25 UTC, Buuh2511 approved these changes

2024-12-30 03:33 UTC, merged

2024-12-30 05:24 UTC, michojekunle commented
> Many thanks for your contribution ! @michojekunle 

Thank you so much @gianalarcon @Buuh2511 for the opportunity to contribute, It's really nice contributing to this project and working with you guys 🙌🏾❤️, Really learnt a lot working on this 💯

 Looking forward to contributing more 🚀🚀