feat/issue 94: partnership card
The-Marquis-Gaming/themarquis-ui pull request #113
Opened 2024-12-23 19:37 UTC by ekumamatthew

issue 94, update landing page to add partnership section 

created a partnership component into the landing page

2024-12-23 20:14 UTC, gianalarcon commented
Good job. @ekumamatthew this PR should point to develop branch, not to main branch

2024-12-24 06:34 UTC, Buuh2511 requested changes
- Spacing between PartnershipCard and Title should be 70px on PC and 22px on MB
- Need to fix responsive, look diff to Figma
![Screenshot 2024-12-24 at 1 33 06 PM](https://github.com/user-attachments/assets/cd6a9cbd-cfd1-4bb4-b8c9-db33f85bf421)
![Screenshot 2024-12-24 at 1 33 55 PM](https://github.com/user-attachments/assets/5466ef6d-55e9-493f-a195-f462413b7277)

2024-12-24 11:23 UTC, Buuh2511 requested changes
1. Still havent fixed : "Spacing between PartnershipCard and Title should be 70px on PC and 22px on MB"
2. Need to fix card on MB not matching Figma for now, first and last card elements must be hidden by 1/3 width for MB version
3. Total width must be limited to class content-fit-center on PC

2024-12-25 07:24 UTC, Buuh2511 commented
1. max-width should be the same with another section such as under image
![image](https://github.com/user-attachments/assets/3f10daa3-4283-410c-9882-8546a9e434ee)

2. still need to margin in MB
![image](https://github.com/user-attachments/assets/3d7180bb-1608-4aca-8ba2-4a110de95d00)

3. there is still some issue when swipe left to right in MB, its look not smooth

2024-12-26 06:56 UTC, ekumamatthew commented
![Screenshot 2024-12-26 075015](https://github.com/user-attachments/assets/f35edcef-8a9f-4c22-8e03-8e003f34d411)

i dont have access to the figma file anymore.
I wasn't available yesterday to apply changes

2024-12-26 09:55 UTC, gianalarcon commented
> ![Screenshot 2024-12-26 075015](https://private-user-images.githubusercontent.com/79433184/398659222-f35edcef-8a9f-4c22-8e03-8e003f34d411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDcxMTEsIm5iZiI6MTczNTIwNjgxMSwicGF0aCI6Ii83OTQzMzE4NC8zOTg2NTkyMjItZjM1ZWRjZWYtOGE5Zi00YzIyLThlMDMtOGUwMDNmMzRkNDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5NTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MDY0YTZkYmY0NjY1YmE3YTBkZDZhOTg5NTE0Y2NlOGQzMTIyNDJjMmQ0MzFmYjIzYjE2MGNlZTlhYmYxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B-Do96DNaK8bzn4zrM1K1iaZ9EpdhcvrRJzjq-SVB2s)
> 
> i dont have access to the figma file anymore. I wasn't available yesterday to apply changes

should be this one. pls try https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=0-1&p=f&t=ME7nY9PoD73iAO3R-0

2024-12-26 10:18 UTC, gianalarcon commented
https://www.figma.com/design/vwxsBUQOK2nKsmzUEDs4xF/Public-Marquis?node-id=0-1&p=f&t=oUhffoyQ4hHNQnhn-0 
@ekumamatthew

2024-12-26 10:20 UTC, ekumamatthew commented
okay. let me get it done

2024-12-28 02:25 UTC, gianalarcon commented
is it ready for review? @ekumamatthew

2024-12-28 02:36 UTC, ekumamatthew commented
Yes pls review I centralise the cards for desktop. Added the padding component width, rechecked margin for mb it is supposed to be 22pixel and thats what i used. then the scroll

2024-12-28 07:13 UTC, Buuh2511 commented
- Need more margin between "Marquis Partnerships" and "Shaping the Future of Gaming Together" on MB
![image](https://github.com/user-attachments/assets/5f5e6edc-e8b6-42f5-9ca6-a013dbdc84ae)

- Do a reponsive on small laptop & tablet screen 
![image](https://github.com/user-attachments/assets/6e7db2cf-4dae-44bc-84c7-f8cc00a97e02)
![image](https://github.com/user-attachments/assets/cfda3d9f-d857-45a4-878f-6aa3d43011da)

- "max-width should be the same with another section such as under image" still havent fixed

2024-12-29 18:57 UTC, ekumamatthew commented
hi @Buuh2511  for the swiper, I'm using a swiper component already existing in the app, can I get a hint on what can possibly cause the swiper not to scroll smoothly to the right? I have gone through the code and you did write some of its component css

2024-12-30 03:07 UTC, Buuh2511 commented
> hi @Buuh2511 for the swiper, I'm using a swiper component already existing in the app, can I get a hint on what can possibly cause the swiper not to scroll smoothly to the right? I have gone through the code and you did write some of its component css

- use this for refer
 <Swiper
          breakpoints={{
            640: {
              slidesPerView: 3.5,
              spaceBetween: 22,
            },
            768: {
              slidesPerView: 3.5,
              spaceBetween: 22,
            },
            1024: {
              slidesPerView: 4,
              spaceBetween: 70,
            },
            1300: {
              slidesPerView: 4,
              spaceBetween: 70,
            },
          }}
          slidesPerView={3.5}
          spaceBetween={22}
          loop={true}
          initialSlide={Math.floor(duplicatedPartners.length / 2)}
        >
          {duplicatedPartners.map((items, index) => {
            return (
              <SwiperSlide key={index}>
                <div className="w-full items-center justify-center flex">
                  <PartnershipCard text={items.name} icon={items.icon} />
                </div>
              </SwiperSlide>
            );
          })}
        </Swiper>

2024-12-30 20:27 UTC, ekumamatthew commented
i added one more card, so that 3.5 on MB can have a smooth loop.. 3.5 is almost 4 and the forward slide acts like an end

2024-12-31 02:43 UTC, gianalarcon commented
Hi @ekumamatthew, sorry, we just updated some requirements, your PR should point to `test-develop` branch pls, change here 
![image](https://github.com/user-attachments/assets/3cc163e1-1efc-431f-8d25-7c8370cfa392)

2024-12-31 02:46 UTC, ekumamatthew commented
Updated

2025-01-02 03:01 UTC, merged